### ISSUE TITLE
Different communities use same name and picture after long running

### ISSUE THREAD

**Issue by kaichaosun** [fluxsocial/flux#219]
**Describe the bug**
I have joined 2 communities, each created by different people, with name and logo different.
After running the application for 1 day, I noticed the 2 communites have same same and logo.

Refresh the page or restart the app didn't solve the issue.

![image](https://user-images.githubusercontent.com/10568673/151282392-aa9e852a-81dc-4af7-a1d9-c84f532996ce.png)

**Comment by jdeepee** [comment]
My guess is this is caused by having the community id which gets used in the getNeighboudhoodMeta (& getNeigbourhoodsChannels) link worker callbacks comes from the parent function which first spawned the job. I think there is some weird async memory stuff going on as each community calls the parent function. I think if the community is passed to the worker in the callbackData object and then consumed by the message callback to update state that should stop weird async stuff going on. Hopefully that makes sense, writing this from my phone so don't have access to full code base right now. Curious to see what you guys think of this theory @fayeed @kaichaosun @leifriksheim

**Comment by fayeed** [comment]
@jdeepee I think your assumptions are correct. The only place where we update the neighbourhood meta is `fetchNeighbourhoodMetadata` worker, but the interesting thing is it shouldn't get triggered unless someone updates the community because we don't update the `groupExpressionRef` @kaichaosun did you update the community before this started happening? Also passing the `communityId` as callbackData fixed this issue.

**Comment by kaichaosun** [comment]
@fayeed I didn't update the community when testing and find this issue.
